service: notes-api
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage,'dev'}
  region: ap-south-1
  profile: sls-test

functions:
  nashir_lambda_authorizer:
    handler: my-authorizer.authHandler
    environment:
      COGNITO_USERPOOL_ID: !Ref myCognitoUserPool
      COGNITO_WEB_CLIENT_ID: !Ref myCognitoUserPoolWebClient

  createNote:
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt notesTable.Arn
    handler: handler.createNote
    events:
      - http:
          method: post
          path: notes
          authorizer: nashir_lambda_authorizer
          
  updateNote:
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt notesTable.Arn
    handler: handler.updateNote
    events:
      - http:
          method: put
          path: notes/{id}
          authorizer: nashir_lambda_authorizer

  deleteNote:
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:DeleteItem
        Resource: !GetAtt notesTable.Arn
    handler: handler.deleteNote
    events:
      - http:
          method: delete
          path: notes/{id}
          authorizer: nashir_lambda_authorizer
          
  getAllNotes:
    environment:
      NOTES_TABLE_NAME: !Ref notesTable
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:Scan
        Resource: !GetAtt notesTable.Arn
    handler: handler.getAllNotes
    events:
      - http:
          method: get
          path: notes
          authorizer:
            name: userPool_authorizer
            type: COGNITO_USER_POOLS
            arn: !GetAtt myCognitoUserPool.Arn # this is the working version
            #arn: ${ssm:/notes/${self:provider.stage}/userPoolArn} # this ssm must already be created to be used like this
                                                # this was introduced just for practice

plugins:
  - serverless-iam-roles-per-function 

# you can add CloudFormation resource templates here
resources:
  Resources: ${file(resources.yml)}